<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\VehicleController;
use Illuminate\Support\Facades\Route;

// Root → redirect to vehicles index
Route::get('/', fn () => redirect()->route('vehicles.index'));

// Dashboard (Breeze default – we repurpose as alias to vehicles)
Route::get('/dashboard', fn () => redirect()->route('vehicles.index'))
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

// ── Authenticated routes ───────────────────────────────────────────────────
Route::middleware('auth')->group(function () {
    // Breeze profile routes
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // VIP2CARS vehicle CRUD
    Route::resource('vehicles', VehicleController::class);
});

// Auth routes (login / register / logout – generated by Breeze)
require __DIR__ . '/auth.php';
